# Generated by Django 5.1.6 on 2025-03-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0002_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
