# Generated by Django 5.1.6 on 2025-03-24 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0010_favoriteproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=150, null=True, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица')),
                ('home', models.CharField(blank=True, max_length=150, null=True, verbose_name='Дом №')),
                ('flat', models.CharField(blank=True, max_length=150, null=True, verbose_name='Квартира №')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('payment', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала заказа')),
                ('shipping', models.BooleanField(default=True, verbose_name='Доставка')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalstore.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='В количестве')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalstore.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalstore.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказ',
                'verbose_name_plural': 'Товары заказов',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('home', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер телефона')),
                ('street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Эл.почта')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='digitalstore.region', verbose_name='Область города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона получаетля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления доставки')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарйи к заказу')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('home', models.CharField(max_length=150, verbose_name='Дом №')),
                ('flat', models.CharField(blank=True, max_length=150, null=True, verbose_name='Квартира №')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalstore.city', verbose_name='Город доставки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalstore.customer', verbose_name='Покупаетля')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalstore.order', verbose_name='Заказ')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalstore.region', verbose_name='Регион доставки')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставок',
            },
        ),
    ]
