# Generated by Django 5.1.6 on 2025-03-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0011_region_customer_order_orderproduct_profile_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='street',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='home',
            new_name='phone',
        ),
    ]
