# Generated by Django 5.1.6 on 2025-03-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0012_rename_street_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество товара'),
        ),
    ]
